export const CREATE_CLIENTE = "CREATE_CLIENTE";
export const READ_CLIENTES = "READ_CLIENTES";
export const UPDATE_CLIENTE = "UPDATE_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";
export const DELETE_ALL_CLIENTES = "DELETE_ALL_CLIENTES";